### ISSUE TITLE
Help with site health issues

### ISSUE THREAD

**Issue by KarolinaSoppa** [dyvenia/site-thescalableway#120]
Hello Lene! 
I've received a site health score report, and we're having some issues again. Could you please take a look at which of those you could fix? Thank you! 

1. ISSUE: **5XX page**, details: https://docs.google.com/spreadsheets/d/1Uz_ODmiZGBK-WAWcTQ3Ta8Y-HzfegE1s55pL7X0vUWo/edit?usp=sharing

2. ISSUE: **5XX page in sitemap**, details: https://docs.google.com/spreadsheets/d/1F9XLBTSJwnqfu9FFaL0RsQbDqj7VisBKVvPCOzl4UKE/edit?usp=sharing

3. ISSUE: **404 page**, details: https://docs.google.com/spreadsheets/d/1mJzLutTs2xYTpDLMOQDDE7c5vi9Sx6-2zvy7BDx_MJM/edit?usp=sharing

4. ISSUE: **4XX page**, details: https://docs.google.com/spreadsheets/d/1Ggc0lMEuwPDoEMro1N6vuduQS-8Hujz_0EZMBU1ruyM/edit?usp=sharing

5. ISSUE: **Orphan page (has no incoming internal links)**; details: https://docs.google.com/spreadsheets/d/1VFFCc1FQh_dvrc9USF8m5l1zIa10F6suXS_EzNUrWOw/edit?usp=sharing

6. ISSUE: **Page has links to broken page**, details: https://docs.google.com/spreadsheets/d/1y-Bq9-FFa8eTQ-hUUrHAd6aGv_tEgSDGsX6FEAMJZ78/edit?usp=sharing

7. ISSUE: **Broken redirect**, details: https://docs.google.com/spreadsheets/d/1fwxk8IyUV2mlWFlFHxnjUtqESSoyFvn8Imruj3XV_tw/edit?usp=sharing

8. ISSUE: **Page has links to redirect**, details: https://docs.google.com/spreadsheets/d/1WDYygfCvvX3XshL9hK5t5XwcPXnTBurrwL9CGnkTxH4/edit?usp=sharing

**Comment by madrilene** [comment]
Don't want you to think I abandoned this! I already added the fix for the author page not being orphan, but the 5XX is still mysterious, especially since it shows pages that should be fixed

**Comment by KarolinaSoppa** [comment]
No worries, in the newest report (from yesterday), there are still the same issues, but let's leave it for a while, I'll let you know what the next crawl will show :) 

<img width="899" height="135" alt="Image" src="https://github.com/user-attachments/assets/d5c6628d-37f8-45d4-a9ca-1d892d085de3" />
